"""Create initial schema

Revision ID: bed40e3d9d57
Revises:
Create Date: 2026-09-11 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed40e3d9d57'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_name', sa.String(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_name')
    )
    op.create_index(op.f('ix_feed_status_id'), 'feed_status', ['id'], unique=False)
    op.create_table('response_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hazard_type', sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', name='hazardtype'), nullable=False),
    sa.Column('region_name', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('plan_data', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('stress_test_score', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_response_plans_id'), 'response_plans', ['id'], unique=False)
    op.create_table('sensor_sites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hazard_type', sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', name='hazardtype'), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('upstream_url_template', sa.Text(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_sites_id'), 'sensor_sites', ['id'], unique=False)
    op.create_table('evacuation_routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('route_name', sa.String(), nullable=False),
    sa.Column('hazard_type', sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', name='hazardtype'), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('capacity_per_hour', sa.Integer(), nullable=True),
    sa.Column('estimated_clearance_hours', sa.Float(), nullable=True),
    sa.Column('alt_route_id', sa.Integer(), nullable=True),
    sa.Column('vulnerable_segments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alt_route_id'], ['evacuation_routes.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['response_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evacuation_routes_id'), 'evacuation_routes', ['id'], unique=False)
    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_site_id', sa.Integer(), nullable=False),
    sa.Column('hazard_type', sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', name='hazardtype'), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_site_id'], ['sensor_sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sensor_readings_id'), 'sensor_readings', ['id'], unique=False)
    op.create_index(op.f('ix_sensor_readings_timestamp'), 'sensor_readings', ['timestamp'], unique=False)
    op.create_table('scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hazard_type', sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', name='hazardtype'), nullable=False),
    sa.Column('generated_from_reading_id', sa.Integer(), nullable=True),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', name='hazardtype'), nullable=False),
    sa.Column('time_horizon_hours', sa.Integer(), nullable=False),
    sa.Column('affected_area', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['generated_from_reading_id'], ['sensor_readings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('plan_stress_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('evacuations_success_rate', sa.Float(), nullable=True),
    sa.Column('resource_coverage', sa.Float(), nullable=True),
    sa.Column('time_to_adequate_response_hours', sa.Float(), nullable=True),
    sa.Column('bottlenecks', sa.Text(), nullable=True),
    sa.Column('cascading_failures_detected', sa.Text(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('recommended_revision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['response_plans.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_stress_tests_id'), 'plan_stress_tests', ['id'], unique=False)
    op.create_table('resource_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('capacity_per_hour', sa.Float(), nullable=True),
    sa.Column('deployment_time_hours', sa.Float(), nullable=True),
    sa.Column('assigned_scenario_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['response_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resource_positions_id'), 'resource_positions', ['id'], unique=False)
    op.create_table('scenario_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('timestamp_offset_hours', sa.Float(), nullable=False),
    sa.Column('magnitude', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cascade_parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cascade_parent_id'], ['scenario_events.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_events_id'), 'scenario_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_events_id'), table_name='scenario_events')
    op.drop_table('scenario_events')
    op.drop_index(op.f('ix_resource_positions_id'), table_name='resource_positions')
    op.drop_table('resource_positions')
    op.drop_index(op.f('ix_plan_stress_tests_id'), table_name='plan_stress_tests')
    op.drop_table('plan_stress_tests')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_sensor_readings_timestamp'), table_name='sensor_readings')
    op.drop_index(op.f('ix_sensor_readings_id'), table_name='sensor_readings')
    op.drop_table('sensor_readings')
    op.drop_index(op.f('ix_evacuation_routes_id'), table_name='evacuation_routes')
    op.drop_table('evacuation_routes')
    op.drop_index(op.f('ix_sensor_sites_id'), table_name='sensor_sites')
    op.drop_table('sensor_sites')
    op.drop_index(op.f('ix_response_plans_id'), table_name='response_plans')
    op.drop_table('response_plans')
    op.drop_index(op.f('ix_feed_status_id'), table_name='feed_status')
    op.drop_table('feed_status')
    # ### end Alembic commands ###