"""Add new hazard types and severity enum

Revision ID: da1a3c15b39d
Revises: bed40e3d9d57
Create Date: 2026-09-11 18:51:40.403325

"""
from __future__ import with_statement

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'da1a3c15b39d'
down_revision = 'bed40e3d9d57'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evacuation_routes', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               existing_nullable=False)

    with op.batch_alter_table('response_plans', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               existing_nullable=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               existing_nullable=False)
        batch_op.alter_column('severity',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('low', 'medium', 'high', 'extreme', name='severity'),
               existing_nullable=False)

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               existing_nullable=False)

    with op.batch_alter_table('sensor_sites', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               existing_nullable=False)

    op.add_column('scenarios', sa.Column('status', sa.Enum('simulating', 'complete', 'expired', name='scenariostatus'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_sites', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.alter_column('severity',
               existing_type=sa.Enum('low', 'medium', 'high', 'extreme', name='severity'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('hazard_type',
               existing_type=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    op.drop_column('scenarios', 'status')

    with op.batch_alter_table('response_plans', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('evacuation_routes', schema=None) as batch_op:
        batch_op.alter_column('hazard_type',
               existing_type=sa.Enum('earthquake', 'flood', 'wildfire', 'cyclone', 'landslide', 'volcanic', 'tsunami', 'rainfall', 'temperature', 'humidity', 'wind_speed', 'wind_gust', name='hazardtype'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###